# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "dev"]
  
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Copy language files
        run: |
          mkdir il8n/fr/docusaurus-plugin-content-docs/current -p
          mkdir il8n/es/docusaurus-plugin-content-docs/current =p
          mkdir il8n/zh-cn/docusaurus-plugin-content-docs/current -p
          cp docs/ il8n/fr/docusaurus-plugin-content-docs/current -r
          cp docs/ il8n/es/docusaurus-plugin-content-docs/current -r
          cp docs/ il8n/zh-cn/docusaurus-plugin-content-docs/current -r
      - name: Configure Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build Project
        run: | 
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
