# Simple workflow for deploying static content to GitHub Pages
name: Deploy Documentation Site

on:
  # Builds run for every push to the default branch
  push:
    branches: [ "main" ]
  # …and on manual dispatch
  workflow_dispatch:

# GitHub Pages v4 now pulls the artifact through the Actions API,
# so it needs `actions: read` in addition to the usual scopes.
permissions:
  contents: read
  pages:    write
  id-token: write
  actions:  read

# One deployment at a time
concurrency:
  group:   "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]   # latest LTS as of mid‑2025

    steps:
      # 1 — checkout repo (v4)
      - name: Checkout
        uses: actions/checkout@v4

      # 2 — enable & configure Pages 
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3 — copy localised docs 
      - name: Copy language files
        run: |
          cp docs/ il8n/fr/docusaurus-plugin-content-docs/current -r
          cp docs/ il8n/es/docusaurus-plugin-content-docs/current -r
          cp docs/ il8n/zh-cn/docusaurus-plugin-content-docs/current -r

      # 4 — setup Node (v4)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # 5 — install deps & build site
      - name: Build project
        run: |
          npm ci
          npm run build

      # 6 — upload the build as a GitHub Pages artifact (v3) :contentReference[oaicite:1]{index=1}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      # 7 — deploy the artifact to Pages (v4) :contentReference[oaicite:2]{index=2}
      - name: Deploy to GitHub Pages
        id:   deployment
        uses: actions/deploy-pages@v4
